<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Xatkit" nsURI="Xatkit" nsPrefix="Xatkit">
  <eClassifiers xsi:type="ecore:EClass" name="XatkitBot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intents" lowerBound="1"
        upperBound="-1" eType="#//Intent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" lowerBound="1"
        upperBound="-1" eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultEntities" lowerBound="1"
        upperBound="-1" eType="#//DefaultEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        upperBound="-1" eType="#//Input" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" lowerBound="1"
        upperBound="-1" eType="#//Entry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="complexEntries" lowerBound="1"
        upperBound="-1" eType="#//ComplexEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synonyms" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="@CointainerVAREntry"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" lowerBound="1"
        upperBound="-1" eType="#//ComplexEntryToken" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEntryToken" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pos" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityToken" eSuperTypes="#//ComplexEntryToken">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralToken" eSuperTypes="#//ComplexEntryToken">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultEntity" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input"/>
</ecore:EPackage>
